### ISSUE TITLE
[not an issue, more of a question] Could we expect an update to this soon to support bones and animations?

### ISSUE THREAD

**Issue by Gamesaw-Drew** [rdb/blender-egg-importer#1]
For the project I am currently a part of, me being able to import bones / animations into blender would be a HUGE help. Do you have an estimate on a time you could get to doing this? Thanks!

**Comment by rdb** [comment]
It is on the todo list, but I first want to fix a few more fundamental issues such as correct coordinate system conversion.

I can't make any promises on when I will get to it, since I only sporadically have time to spend on this, and animation is a rather daunting task.  I will have to implement skinning first.

The more interest there is in this feature, the higher priority it will have, though.

**Comment by rdb** [comment]
Bones and skinning are now supported.  Animations not yet.  I'll look into how much effort this is going to be.

**Comment by rdb** [comment]
Skeletal animations are now supported, experimentally.  Here's Roaming Ralph:

http://rdb.name/blender-roaming-ralph.webm
